---
- name: Playbook
  hosts: apphosts
  tasks:
    - name: install java-17-amazon-corretto and mysql
      become: yes
      yum:
        name: "{{ packages }}"
        state: installed
      vars:
        packages:
        - java-17-amazon-corretto
        - mysql

    - name: copy app and user.sql
      copy:
        src: ~/git-files/spring-petclinic/target/app
        dest: ~/
    
    - name: test
      debug:
        var: dbendpoint
    - debug:
        var: dbsecret

    - name: log in to mysql server
      shell: mysql -h {{ dbendpoint }} -u admin --password='{{ dbsecret }}' < /home/ec2-user/app/user.sql

    - name: create MYSQL_URL en, start app
      shell: nohup java -jar /home/ec2-user/app/spring-petclinic-3.1.0-SNAPSHOT.jar --spring.profiles.active=mysql  > /dev/null 2>&1 &
      environment:
        MYSQL_URL: "jdbc:mysql://{{ dbendpoint }}:3306/petclinic"

